//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHOCore.Site.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_DN_ContactUs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_DN_ContactUs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CHOCore.Site.Resources.Views.DN.ContactUs", typeof(Views_DN_ContactUs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;small-3 cell&quot;&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;small-9 cell&quot;&gt;
        ///          &lt;p&gt;Didn&apos;t find what you were looking for? Ask CanadaHelps:&lt;/p&gt;
        ///          &lt;p&gt;&lt;span class=&quot;ion-information-circled&quot;&gt;&lt;/span&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;This request will reach CanadaHelps&lt;/p&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        internal static string AskCanadaHelpsMessage {
            get {
                return ResourceManager.GetString("AskCanadaHelpsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt; Help/Contact CanadaHelps&lt;/h3&gt;.
        /// </summary>
        internal static string ContactUsHeader {
            get {
                return ResourceManager.GetString("ContactUsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;small-3 cell&quot;&gt;
        ///        &lt;label for=&quot;middle-label&quot; class=&quot;text-right middle&quot;&gt;Local&lt;/label&gt;
        ///      &lt;/div&gt;
        ///      &lt;div class=&quot;small-9 cell&quot;&gt;
        ///        1-416-628-6948
        ///&lt;p&gt;9 AM - 5 PM Eastern Monday to Friday&lt;/p&gt;
        ///   &lt;p&gt;Phone and email not available for Canadian statutory  holidays.&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string LocalInfoMessage {
            get {
                return ResourceManager.GetString("LocalInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;small-3 cell&quot;&gt;
        ///          &lt;label for=&quot;middle-label&quot; class=&quot;text-right middle required-field&quot;&gt;NEED YOUR TAX RECEIPT(S)?&lt;/label&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;small-9 cell&quot;&gt;
        ///          &lt;a href=&quot;/ReceiptDownload.aspx&quot; target=&quot;_blank&quot; class=&quot;cdn-contact-us-tax-receipt-link&quot;&gt;Download them here&lt;/a&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        internal static string NeedYourReceiptMessage {
            get {
                return ResourceManager.GetString("NeedYourReceiptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;small-3 cell&quot;&gt;
        ///          &lt;label for=&quot;middle-label&quot; class=&quot;text-right middle required-field&quot;&gt;QUESTIONS?&lt;/label&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;small-9 cell&quot;&gt;
        ///          &lt;a href=&quot;http://donorhelp.canadahelps.org/en/&quot; class=&quot;cdn-contact-us-faq-link&quot; target=&quot;_blank&quot;&gt;Find answers here&lt;/a&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        internal static string QuestionsMessage {
            get {
                return ResourceManager.GetString("QuestionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendButtonText {
            get {
                return ResourceManager.GetString("SendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;small-3 cell&quot;&gt;
        ///        &lt;label for=&quot;middle-label&quot; class=&quot;text-right middle&quot;&gt;Toll-free&lt;/label&gt;
        ///      &lt;/div&gt;
        ///      &lt;div class=&quot;small-9 cell&quot;&gt;
        ///        1-877-755-1595
        ///      &lt;/div&gt;.
        /// </summary>
        internal static string TollFreeMessage {
            get {
                return ResourceManager.GetString("TollFreeMessage", resourceCulture);
            }
        }
    }
}
