//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHOCore.Site.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Shared_Components_MainTab_Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Shared_Components_MainTab_Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CHOCore.Site.Resources.Views.Shared.Components.MainTab.Default", typeof(Views_Shared_Components_MainTab_Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string tab0NavText {
            get {
                return ResourceManager.GetString("tab0NavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/MyCH/Welcome.aspx.
        /// </summary>
        internal static string tab0NavUrl {
            get {
                return ResourceManager.GetString("tab0NavUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string tab1NavText {
            get {
                return ResourceManager.GetString("tab1NavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/MyCH/Settings.aspx.
        /// </summary>
        internal static string tab1NavUrl {
            get {
                return ResourceManager.GetString("tab1NavUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations &amp;amp; Receipts.
        /// </summary>
        internal static string tab2NavText {
            get {
                return ResourceManager.GetString("tab2NavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/MyCH/DonationsReceipts.aspx.
        /// </summary>
        internal static string tab2NavUrl {
            get {
                return ResourceManager.GetString("tab2NavUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Donations.
        /// </summary>
        internal static string tab3NavText {
            get {
                return ResourceManager.GetString("tab3NavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/MyCH/MonthlyGiving.aspx.
        /// </summary>
        internal static string tab3NavUrl {
            get {
                return ResourceManager.GetString("tab3NavUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string tab4NavText {
            get {
                return ResourceManager.GetString("tab4NavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/Favourites/.
        /// </summary>
        internal static string tab4NavUrl {
            get {
                return ResourceManager.GetString("tab4NavUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundraising Pages.
        /// </summary>
        internal static string tab5NavText {
            get {
                return ResourceManager.GetString("tab5NavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/MyCH/FundraisingPages.aspx.
        /// </summary>
        internal static string tab5NavUrl {
            get {
                return ResourceManager.GetString("tab5NavUrl", resourceCulture);
            }
        }
    }
}
