//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHOCore.Site.Resources.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactUsViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactUsViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CHOCore.Site.Resources.ViewModels.ContactUsViewModel", typeof(ContactUsViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email is not valid, please provide valid email address..
        /// </summary>
        internal static string invalidEmail {
            get {
                return ResourceManager.GetString("invalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email..
        /// </summary>
        internal static string requiredSenderEmail {
            get {
                return ResourceManager.GetString("requiredSenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please describe your issue..
        /// </summary>
        internal static string requriedSenderMessage {
            get {
                return ResourceManager.GetString("requriedSenderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name..
        /// </summary>
        internal static string requriedSenderName {
            get {
                return ResourceManager.GetString("requriedSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your subject..
        /// </summary>
        internal static string requriedSubject {
            get {
                return ResourceManager.GetString("requriedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR EMAIL.
        /// </summary>
        internal static string senderEmail {
            get {
                return ResourceManager.GetString("senderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR MESSAGE.
        /// </summary>
        internal static string senderMessage {
            get {
                return ResourceManager.GetString("senderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR NAME.
        /// </summary>
        internal static string senderName {
            get {
                return ResourceManager.GetString("senderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR SUBJECT.
        /// </summary>
        internal static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
    }
}
